- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    bluetooth: true
    container: true
  roles:
    - base
    - audio
    - bluetooth
    - gui
    - dev
    - repos
    - flatpak
    - etckeeper

# vim: ft=yaml.ansible
