- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    bluetooth: true
  roles:
    - base
    - bootloader
    - audio
    - bluetooth
    - gui
    - dev
    - docker
    - repos
    - flatpak
    - etckeeper
    - mandb

# vim: ft=yaml.ansible
