- name: Install flatpak
  pacman: name=flatpak
  tags: packages

- name: Add flathub flatpak remote
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags: packages
